package gateway

type EventType string

const (
	EventTypeChatMessageCreated            EventType = "ChatMessageCreated"
	EventTypeChatMessageUpdated            EventType = "ChatMessageUpdated"
	EventTypeChatMessageDeleted            EventType = "ChatMessageDeleted"
	EventTypeTeamMemberJoined              EventType = "TeamMemberJoined"
	EventTypeTeamMemberRemoved             EventType = "TeamMemberRemoved"
	EventTypeTeamMemberBanned              EventType = "TeamMemberBanned"
	EventTypeTeamMemberUnbanned            EventType = "TeamMemberUnbanned"
	EventTypeTeamMemberUpdated             EventType = "TeamMemberUpdated"
	EventTypeTeamRolesUpdated              EventType = "teamRolesUpdated"
	EventTypeTeamChannelCreated            EventType = "TeamChannelCreated"
	EventTypeTeamChannelUpdated            EventType = "TeamChannelUpdated"
	EventTypeTeamChannelDeleted            EventType = "TeamChannelDeleted"
	EventTypeTeamWebhookCreated            EventType = "TeamWebhookCreated"
	EventTypeTeamWebhookUpdated            EventType = "TeamWebhookUpdated"
	EventTypeDocCreated                    EventType = "DocCreated"
	EventTypeDocUpdated                    EventType = "DocUpdated"
	EventTypeDocDeleted                    EventType = "DocDeleted"
	EventTypeCalendarEventCreated          EventType = "CalendarEventCreated"
	EventTypeCalendarEventUpdated          EventType = "CalendarEventUpdated"
	EventTypeCalendarEventDeleted          EventType = "CalendarEventDeleted"
	EventTypeForumTopicCreated             EventType = "ForumTopicCreated"
	EventTypeForumTopicUpdated             EventType = "ForumTopicUpdated"
	EventTypeForumTopicDeleted             EventType = "ForumTopicDeleted"
	EventTypeForumTopicPinned              EventType = "ForumTopicPinned"
	EventTypeForumTopicUnpinned            EventType = "ForumTopicUnpinned"
	EventTypeForumTopicLocked              EventType = "ForumTopicLocked"
	EventTypeForumTopicUnlocked            EventType = "ForumTopicUnlocked"
	EventTypeCalendarEventRsvpUpdated      EventType = "CalendarEventRsvpUpdated"
	EventTypeCalendarEventRsvpManyUpdated  EventType = "CalendarEventRsvpManyUpdated"
	EventTypeCalendarEventRsvpDeleted      EventType = "CalendarEventRsvpDeleted"
	EventTypeListItemCreated               EventType = "ListItemCreated"
	EventTypeListItemUpdated               EventType = "ListItemUpdated"
	EventTypeListItemDeleted               EventType = "ListItemDeleted"
	EventTypeListItemCompleted             EventType = "ListItemCompleted"
	EventTypeListItemUncompleted           EventType = "ListItemUncompleted"
	EventTypeChannelMessageReactionCreated EventType = "ChannelMessageReactionCreated"
	EventTypeChannelMessageReactionDeleted EventType = "ChannelMessageReactionDeleted"
)
